apiVersion: v1
kind: Service
metadata:
  name: service-tb
  labels:
    app: service-tb

spec:
  type: LoadBalancer
  selector:          
    app: pod-tb

  ports:
    - name: credentials-api-svc-port
      port: 8001
      protocol: TCP
      targetPort: 7000   # Target port for the FastAPI container

    - name: router-api-svc-port
      port: 8000
      protocol: TCP
      targetPort: 8000   # Target port for the second FastAPI container

    - name: ui-svc-port
      port: 7999
      protocol: TCP
      targetPort: 8501   # Exposed port in the ui container